language: node_js

node_js:
  - 8
  - 6

jobs:
  include:
    - stage: release
      if: tag IS present
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run build && npm run release
